version: '3'
services:
  capstoneproject:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
         DPSQL_HOSTNAME: psql
         DBOOT_NAME: kafka
         KAFKA-IP: 29092
      restart: always
      container_name: capstone_project
      networks:
        -  first_network
      depends_on:
        - psql
        - zookeeper
        - kafka


  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - first_network


  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
        - "9092:9092"
    environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL_SAME_HOST://:9092
          KAFKA_ADVERTISED_LISTENERS: EXTERNAL_SAME_HOST://127.0.0.1:9092,INTERNAL://kafka:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
          KAFKA_CREATE_TOPICS: "ORDER:1:1,ORDER_UPDATE:1:1"
    networks:
        -  first_network
    depends_on:
        - zookeeper





  psql:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - first_network
    volumes:
      - psql_volumes:/var/lib/postgresql/data
    container_name: psql


networks:
  first_network:

volumes:
  psql_volumes: